mytodo/urls.py
from django.urls import path
from . import views

app_name = "mytodo"

urlpatterns = [
    path("", views.index, name="index"),
    path("done/<int:pk>/", views.todo_done, name="todo_done"),
    path("undo/<int:pk>/", views.todo_undo, name="todo_undo"),
    path("delete/<int:pk>/", views.todo_delete, name="todo_delete"),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mytodo.urls')),
]

mytodo/models.py
from django.db import models

class Todo(models.Model):
    todo_text = models.CharField(max_length=100, blank=False)
    todo_done = models.BooleanField(default=False)

    def __str__(self):
        return self.todo_text

mytodo/forms.py
from django import forms

class AddTodoForm(forms.Form):
    new_todo = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={"placeholder": "New Todo", "size": "40", "autofocus": "autofocus"}))

    def clean_new_todo(self):
        new_todo = self.cleaned_data["new_todo"]

        return new_todo

mytodo/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Todo
from .forms import AddTodoForm

# display all todos
def index(request):
    
    if request.method == "POST":
        form = AddTodoForm(request.POST)
        if form.is_valid():
            new_todo = Todo()
            new_todo.todo_text = form.cleaned_data["new_todo"]
            new_todo.save()
            return HttpResponseRedirect(reverse("mytodo:index"))
    elif request.method == "GET":
        form = AddTodoForm()

    todos = Todo.objects.all().order_by("-pk")
    context = {
        "form": form,
        "todo_list": todos,
    }
    return render(request, "index.html", context)

# to checkout a todo
def todo_done(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.todo_done = True
    todo.save()
    return HttpResponseRedirect(reverse("mytodo:index"))

# to uncheck a todo
def todo_undo(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.todo_done = False
    todo.save()
    return HttpResponseRedirect(reverse("mytodo:index"))

# to delete a todo
def todo_delete(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    return HttpResponseRedirect(reverse("mytodo:index"))

templates/base.html
{% load static %}

<!DOCTYPE html>
	<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<html>
  <head>
    <meta charset="utf-8">
    <title>Todo App</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- font-awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet">  
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/todo.css' %}">
  </head>
  <body>
    <center>
        <div class="container-fluid">
            <div class="jumbotron">
                <h1 style="font-family: Monoton;">MY TODO</h1>
            </div>
            {% block content %}
            {% endblock %} 
        </div>
    </center>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <form class="form-group" action="" method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        {{ field }}
        {% endfor %}
        <button class="btn btn-primary" type="submit"><i class="fa fa-plus"></i></button>
    </form>
    <div>
        <div class="list-group">
            {% if todo_list %}
                {% for todo in todo_list %}
                    <div class="list-group-item d-flex justify-content-between align-items-center {% if todo.todo_done %}list-group-item-success{% endif %}">
                        <span {% if todo.todo_done %}style="text-decoration-line: line-through;"{% endif %}>{{ todo.todo_text }}</span>
                    <div class="btn-group">
                        {% if not todo.todo_done %}
                            <a href="{% url 'mytodo:todo_done' pk=todo.pk %}"><button class="btn btn-success" type="button"><i class="fa fa-check"></i></button></a>
                        {% else %}
                            <a href="{% url 'mytodo:todo_undo' pk=todo.pk %}"><button class="btn btn-outline-secondary" type="button"><i class="fa fa-undo"></i></button></a>
                        {% endif %}
                        <a href="{% url 'mytodo:todo_delete' pk=todo.pk %}"><button class="btn btn-danger" type="button"><i class="fa fa-trash"></i></button></a>
                    </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock %}        